### ISSUE TITLE
1.19.2 Crash upon Startup

### ISSUE THREAD

**Issue by SkullHunter55** [Bennyboy1695/DisableStructures#2]
Like mentioned by one of the previous guys on curse, the mod crashes in 1.19.2 when trying to start it up.
I hope you'll be able to fix it, as I'd really like to use your mod!

[latest.log](https://github.com/Bennyboy1695/DisableStructures/files/12138753/latest.log)

**Comment by Bennyboy1695** [comment]
Fixed in [c466ab2](https://github.com/Bennyboy1695/DisableStructures/commit/c466ab20b9b51605eecf3bea26d2a5702c3d5615)
Will upload to curseforge and modrinth now (will take time for them to verify the file though I expect)
